import type { Metadata } from "next";
import { Poppins as CurrentFont } from "next/font/google";
import "@/styles/globals.css";
import { AuthProvider } from "@/lib/contexts/auth/auth-context";
import { ThemeProvider } from "@/components/theme-provider";
import AudioProvider from "@/lib/contexts/audio-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const font = CurrentFont({ weight: ["400", "700"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="theme-mixboos dark">
      <body
        className={`${font.className}  antialiased`}
        suppressHydrationWarning
      >
        <AuthProvider>
          <AudioProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
            </ThemeProvider>
          </AudioProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
