/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mixUploadRouteImport } from './routes/(mix)/upload'
import { Route as authMixIdRouteImport } from './routes/(auth)/mix/$id'
import { Route as authLiveCreateRouteImport } from './routes/(auth)/live/create'
import { Route as mixUserMixIndexRouteImport } from './routes/(mix)/$user/$mix/index'
import { Route as authDashboardMixesIndexRouteImport } from './routes/(auth)/dashboard/mixes/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mixUploadRoute = mixUploadRouteImport.update({
  id: '/(mix)/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const authMixIdRoute = authMixIdRouteImport.update({
  id: '/(auth)/mix/$id',
  path: '/mix/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const authLiveCreateRoute = authLiveCreateRouteImport.update({
  id: '/(auth)/live/create',
  path: '/live/create',
  getParentRoute: () => rootRouteImport,
} as any)
const mixUserMixIndexRoute = mixUserMixIndexRouteImport.update({
  id: '/(mix)/$user/$mix/',
  path: '/$user/$mix/',
  getParentRoute: () => rootRouteImport,
} as any)
const authDashboardMixesIndexRoute = authDashboardMixesIndexRouteImport.update({
  id: '/(auth)/dashboard/mixes/',
  path: '/dashboard/mixes/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof mixUploadRoute
  '/live/create': typeof authLiveCreateRoute
  '/mix/$id': typeof authMixIdRoute
  '/dashboard/mixes': typeof authDashboardMixesIndexRoute
  '/$user/$mix': typeof mixUserMixIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof mixUploadRoute
  '/live/create': typeof authLiveCreateRoute
  '/mix/$id': typeof authMixIdRoute
  '/dashboard/mixes': typeof authDashboardMixesIndexRoute
  '/$user/$mix': typeof mixUserMixIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(mix)/upload': typeof mixUploadRoute
  '/(auth)/live/create': typeof authLiveCreateRoute
  '/(auth)/mix/$id': typeof authMixIdRoute
  '/(auth)/dashboard/mixes/': typeof authDashboardMixesIndexRoute
  '/(mix)/$user/$mix/': typeof mixUserMixIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/live/create'
    | '/mix/$id'
    | '/dashboard/mixes'
    | '/$user/$mix'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/live/create'
    | '/mix/$id'
    | '/dashboard/mixes'
    | '/$user/$mix'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/(mix)/upload'
    | '/(auth)/live/create'
    | '/(auth)/mix/$id'
    | '/(auth)/dashboard/mixes/'
    | '/(mix)/$user/$mix/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  mixUploadRoute: typeof mixUploadRoute
  authLiveCreateRoute: typeof authLiveCreateRoute
  authMixIdRoute: typeof authMixIdRoute
  authDashboardMixesIndexRoute: typeof authDashboardMixesIndexRoute
  mixUserMixIndexRoute: typeof mixUserMixIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(mix)/upload': {
      id: '/(mix)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof mixUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/mix/$id': {
      id: '/(auth)/mix/$id'
      path: '/mix/$id'
      fullPath: '/mix/$id'
      preLoaderRoute: typeof authMixIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/live/create': {
      id: '/(auth)/live/create'
      path: '/live/create'
      fullPath: '/live/create'
      preLoaderRoute: typeof authLiveCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(mix)/$user/$mix/': {
      id: '/(mix)/$user/$mix/'
      path: '/$user/$mix'
      fullPath: '/$user/$mix'
      preLoaderRoute: typeof mixUserMixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/dashboard/mixes/': {
      id: '/(auth)/dashboard/mixes/'
      path: '/dashboard/mixes'
      fullPath: '/dashboard/mixes'
      preLoaderRoute: typeof authDashboardMixesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  mixUploadRoute: mixUploadRoute,
  authLiveCreateRoute: authLiveCreateRoute,
  authMixIdRoute: authMixIdRoute,
  authDashboardMixesIndexRoute: authDashboardMixesIndexRoute,
  mixUserMixIndexRoute: mixUserMixIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
