/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as mixUploadRouteImport } from './routes/(mix)/upload'
import { Route as AuthenticatedMixIdRouteImport } from './routes/_authenticated/mix/$id'
import { Route as AuthenticatedLiveCreateRouteImport } from './routes/_authenticated/live/create'
import { Route as AuthenticatedDashboardMixesIndexRouteImport } from './routes/_authenticated/dashboard/mixes/index'
import { Route as mixUserMixIndexRouteImport } from './routes/(mix)/$user/$mix/index'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const mixUploadRoute = mixUploadRouteImport.update({
  id: '/(mix)/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMixIdRoute = AuthenticatedMixIdRouteImport.update({
  id: '/mix/$id',
  path: '/mix/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLiveCreateRoute = AuthenticatedLiveCreateRouteImport.update({
  id: '/live/create',
  path: '/live/create',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardMixesIndexRoute =
  AuthenticatedDashboardMixesIndexRouteImport.update({
    id: '/dashboard/mixes/',
    path: '/dashboard/mixes/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const mixUserMixIndexRoute = mixUserMixIndexRouteImport.update({
  id: '/(mix)/$user/$mix/',
  path: '/$user/$mix/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof mixUploadRoute
  '/live/create': typeof AuthenticatedLiveCreateRoute
  '/mix/$id': typeof AuthenticatedMixIdRoute
  '/$user/$mix': typeof mixUserMixIndexRoute
  '/dashboard/mixes': typeof AuthenticatedDashboardMixesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/upload': typeof mixUploadRoute
  '/live/create': typeof AuthenticatedLiveCreateRoute
  '/mix/$id': typeof AuthenticatedMixIdRoute
  '/$user/$mix': typeof mixUserMixIndexRoute
  '/dashboard/mixes': typeof AuthenticatedDashboardMixesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/(mix)/upload': typeof mixUploadRoute
  '/_authenticated/live/create': typeof AuthenticatedLiveCreateRoute
  '/_authenticated/mix/$id': typeof AuthenticatedMixIdRoute
  '/(mix)/$user/$mix/': typeof mixUserMixIndexRoute
  '/_authenticated/dashboard/mixes/': typeof AuthenticatedDashboardMixesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/live/create'
    | '/mix/$id'
    | '/$user/$mix'
    | '/dashboard/mixes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/upload'
    | '/live/create'
    | '/mix/$id'
    | '/$user/$mix'
    | '/dashboard/mixes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/(mix)/upload'
    | '/_authenticated/live/create'
    | '/_authenticated/mix/$id'
    | '/(mix)/$user/$mix/'
    | '/_authenticated/dashboard/mixes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  mixUploadRoute: typeof mixUploadRoute
  mixUserMixIndexRoute: typeof mixUserMixIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(mix)/upload': {
      id: '/(mix)/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof mixUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/mix/$id': {
      id: '/_authenticated/mix/$id'
      path: '/mix/$id'
      fullPath: '/mix/$id'
      preLoaderRoute: typeof AuthenticatedMixIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/live/create': {
      id: '/_authenticated/live/create'
      path: '/live/create'
      fullPath: '/live/create'
      preLoaderRoute: typeof AuthenticatedLiveCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/mixes/': {
      id: '/_authenticated/dashboard/mixes/'
      path: '/dashboard/mixes'
      fullPath: '/dashboard/mixes'
      preLoaderRoute: typeof AuthenticatedDashboardMixesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(mix)/$user/$mix/': {
      id: '/(mix)/$user/$mix/'
      path: '/$user/$mix'
      fullPath: '/$user/$mix'
      preLoaderRoute: typeof mixUserMixIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedLiveCreateRoute: typeof AuthenticatedLiveCreateRoute
  AuthenticatedMixIdRoute: typeof AuthenticatedMixIdRoute
  AuthenticatedDashboardMixesIndexRoute: typeof AuthenticatedDashboardMixesIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedLiveCreateRoute: AuthenticatedLiveCreateRoute,
  AuthenticatedMixIdRoute: AuthenticatedMixIdRoute,
  AuthenticatedDashboardMixesIndexRoute: AuthenticatedDashboardMixesIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  mixUploadRoute: mixUploadRoute,
  mixUserMixIndexRoute: mixUserMixIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
