/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as AuthedImport } from './routes/_authed'
import { Route as DebugRouteImport } from './routes/debug/route'
import { Route as IndexImport } from './routes/index'
import { Route as UploadIndexImport } from './routes/upload/index'
import { Route as DebugIndexImport } from './routes/debug/index'
import { Route as LiveCreateImport } from './routes/live/create'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthedRoute = AuthedImport.update({
  id: '/_authed',
  getParentRoute: () => rootRoute,
} as any)

const DebugRouteRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const UploadIndexRoute = UploadIndexImport.update({
  id: '/upload/',
  path: '/upload/',
  getParentRoute: () => rootRoute,
} as any)

const DebugIndexRoute = DebugIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DebugRouteRoute,
} as any)

const LiveCreateRoute = LiveCreateImport.update({
  id: '/live/create',
  path: '/live/create',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRoute
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/live/create': {
      id: '/live/create'
      path: '/live/create'
      fullPath: '/live/create'
      preLoaderRoute: typeof LiveCreateImport
      parentRoute: typeof rootRoute
    }
    '/debug/': {
      id: '/debug/'
      path: '/'
      fullPath: '/debug/'
      preLoaderRoute: typeof DebugIndexImport
      parentRoute: typeof DebugRouteImport
    }
    '/upload/': {
      id: '/upload/'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

interface DebugRouteRouteChildren {
  DebugIndexRoute: typeof DebugIndexRoute
}

const DebugRouteRouteChildren: DebugRouteRouteChildren = {
  DebugIndexRoute: DebugIndexRoute,
}

const DebugRouteRouteWithChildren = DebugRouteRoute._addFileChildren(
  DebugRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteRouteWithChildren
  '': typeof AuthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/live/create': typeof LiveCreateRoute
  '/debug/': typeof DebugIndexRoute
  '/upload': typeof UploadIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/live/create': typeof LiveCreateRoute
  '/debug': typeof DebugIndexRoute
  '/upload': typeof UploadIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/debug': typeof DebugRouteRouteWithChildren
  '/_authed': typeof AuthedRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRoute
  '/live/create': typeof LiveCreateRoute
  '/debug/': typeof DebugIndexRoute
  '/upload/': typeof UploadIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/debug'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/live/create'
    | '/debug/'
    | '/upload'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/logout'
    | '/signup'
    | '/live/create'
    | '/debug'
    | '/upload'
  id:
    | '__root__'
    | '/'
    | '/debug'
    | '/_authed'
    | '/login'
    | '/logout'
    | '/signup'
    | '/live/create'
    | '/debug/'
    | '/upload/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DebugRouteRoute: typeof DebugRouteRouteWithChildren
  AuthedRoute: typeof AuthedRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRoute
  LiveCreateRoute: typeof LiveCreateRoute
  UploadIndexRoute: typeof UploadIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DebugRouteRoute: DebugRouteRouteWithChildren,
  AuthedRoute: AuthedRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRoute,
  LiveCreateRoute: LiveCreateRoute,
  UploadIndexRoute: UploadIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/debug",
        "/_authed",
        "/login",
        "/logout",
        "/signup",
        "/live/create",
        "/upload/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/debug": {
      "filePath": "debug/route.tsx",
      "children": [
        "/debug/"
      ]
    },
    "/_authed": {
      "filePath": "_authed.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/live/create": {
      "filePath": "live/create.tsx"
    },
    "/debug/": {
      "filePath": "debug/index.tsx",
      "parent": "/debug"
    },
    "/upload/": {
      "filePath": "upload/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
